version: '3.9'

services:
  mariadb:
    image: mariadb:10.7
    container_name: mariadb-svr1
    ports:
      - 3306:3306
    volumes:
      - ./.data/mariadb:/var/lib/mysql
    environment:
      TZ: 'America/Argentina/Buenos_Aires'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_ROOT_PASSWORD: '123456789'
      MYSQL_USER: 'todoapp_user'
      MYSQL_PASSWORD: 'secreto'
      MYSQL_DATABASE: 'todoapp_dev'
